### ISSUE TITLE
Development Requests

### ISSUE THREAD

**Issue by EOGrady21** [EOGrady21/VPR_viewer#12]
After meeting with collaborators (@kevinsorochan & @cathjohnson), a series of development requests and tweaks have been proposed.

Short term:
- [x] Update app name, 'VPR viewer'
- [x] All concentration units should be in m^3
- [x] Allow mid range size sorting for img gallery
- [x] change QC sliders to numeric range inputs
- [x] add loading icon
- [x] QC ranges should match data range

Long term:
- [ ] #13
- [ ] interactive plots, showing ROI images (using leaflet?)

**Comment by kevinsorochan** [comment]
Maybe consider Plotly for interactive plotting
