### ISSUE TITLE
investigate other potential uses for image metadata once loaded for all images

### ISSUE THREAD

**Issue by EOGrady21** [EOGrady21/VPR_viewer#13]

**Comment by EOGrady21** [comment]
Pulling this task to it's own issue for further discussion. 

Would it be useful to researchers to look at a size distribution of image data within the app? [@kevinsorochan ]

This could be used as a *very rough* proxy for organism size distribution, before processing. 

I think this plot would need it's own tab maybe? but it would be easy to work up since the image metadata has been read in for the gallery.

**Comment by kevinsorochan** [comment]
I am not sure about this. My initial answer is probably no.
